解决spark2.2.3在python3.7环境下的bug:19/03/29 19:05:50 ERROR executor.Executor: Exception in task 0.0 in stage 0.0 (TID 0)                               org.apache.spark.api.python.PythonException: Traceback (most recent call last):                                 File "/usr/local/spark/python/pyspark/rdd.py", line 1326, in takeUpToNumLeft                                   yield next(iterator)                               StopIteration
                              The above exception was the direct cause of the following exception:

                              Traceback (most recent call last):
                                File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 196, in main
                                  process()
                                File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 191, in process
                                  serializer.dump_stream(func(split_index, iterator), outfile)
                                File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
                                  vs = list(itertools.islice(iterator, batch))
                              RuntimeError: generator raised StopIteration